### ISSUE TITLE
File format documentation

### ISSUE THREAD

**Issue by paul35621** [lfuelling/gtasa-savegame-editor#18]
If someone gives me push access I'll upload the documentation from [paulinternet.nl/sadoc](https://www.paulinternet.nl/sadoc). I'll just make a folder /doc and put it there.

The documentation contains one PHP file index.php. I think it would be useful if someone translates this to Javascript so the documentation can be viewed without a web server.

As soon as there is a URL on github that can be used to view the documentation, I'll remove the documentation from paulinternet.nl and make a redirect.

**Comment by lfuelling** [comment]
Hi Paul

I added you as collaborator, push away :)

**Comment by lfuelling** [comment]
solved in bc0f7d29f7d848dde7bfdf40c2a69b2be986e9e1

**Comment by lfuelling** [comment]
@paul35621 I created a `docs` branch, where the converted docs are now. (I used React)

I also made it available using GitHub Pages: https://lfuelling.github.io/gtasa-savegame-editor/#/
