### ISSUE TITLE
Fix bug in save menu

### ISSUE THREAD

**Issue by lfuelling** [lfuelling/gtasa-savegame-editor#5]
Apparently, if you load a game the save menu will be disabled until you delete a savegame. Even when there are free slots.

**Comment by lfuelling** [comment]
This seems to be some kind of race condition. On Windows this works fine now because there is a short lag when you load a savegame. On macOS there's no lag and therefore the `isSavegameLoaded` poll is actually done before the savegame finished loading.

Workaround on macOS:

1. Load the desired save, change a few things
2. Check if the "save" menu is available (not greyed out)
3. If it is, just save as usual
4. If it **isn't** delete one of your savegames (most reasonably the one you've just edited)
5. You should be able to save now.

**Comment by paul35621** [comment]
I don't have this issue on Linux (Debian 9, KDE 5).
